services:
    terminal42_shortlink.controller.shortlink:
        class: Terminal42\ShortlinkBundle\Controller\ShortlinkController
        arguments:
            - '@doctrine'
            - '%terminal42_shortlink.log_ip%'
        tags:
            - { name: controller.service_arguments }

    terminal42_shortlink.hashids:
        class: Hashids\Hashids
        arguments: ['%terminal42_shortlink.salt%']

    terminal42_shortlink.listener.dca_label:
        class: Terminal42\ShortlinkBundle\EventListener\DataContainer\ShortlinkLabelListener
        arguments:
            - '@terminal42_shortlink.repository.shortlink'
            - '@terminal42_shortlink.hashids'
            - '@router.request_context'
            - '%terminal42_shortlink.host%'
        tags:
            - { name: contao.callback, table: tl_terminal42_shortlink, target: list.label.label }

    terminal42_shortlink.listener.dca_permission:
        class: Terminal42\ShortlinkBundle\EventListener\DataContainer\ShortlinkPermissionListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: contao.callback, table: tl_terminal42_shortlink, target: config.onload }
            - { name: contao.callback, table: tl_terminal42_shortlink, target: list.operations.edit.button }
            - { name: contao.callback, table: tl_terminal42_shortlink, target: list.operations.copy.button }
            - { name: contao.callback, table: tl_terminal42_shortlink, target: list.operations.delete.button }
            - { name: contao.callback, table: tl_terminal42_shortlink, target: list.operations.toggle.button }

    terminal42_shortlink.routing.router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments:
            - '@router.request_context'
            - '@terminal42_shortlink.routing.nested_matcher'
            - '@terminal42_shortlink.routing.route_generator'
            - ''
            - '@event_dispatcher'
            - '@terminal42_shortlink.routing.route_provider'
        tags:
            - { name: router, priority: 80 }

    terminal42_shortlink.routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments:
            - '@terminal42_shortlink.routing.route_provider'
            - '@terminal42_shortlink.routing.final_matcher'

    terminal42_shortlink.routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments:
            - '@terminal42_shortlink.routing.dummy_collection'
            - '@terminal42_shortlink.routing.dummy_context'

    terminal42_shortlink.routing.dummy_context:
        class: Symfony\Component\Routing\RequestContext

    terminal42_shortlink.routing.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection

    terminal42_shortlink.routing.route_provider:
        class: Terminal42\ShortlinkBundle\Routing\RouteProvider
        arguments:
            - '@terminal42_shortlink.repository.shortlink'
            - '@terminal42_shortlink.hashids'
            - '%terminal42_shortlink.host%'

    terminal42_shortlink.routing.route_generator:
        class: Symfony\Cmf\Component\Routing\ProviderBasedGenerator
        arguments:
            - '@terminal42_shortlink.routing.route_provider'
            - '@logger'

    terminal42_shortlink.repository.shortlink:
        class: Terminal42\ShortlinkBundle\Repository\ShortlinkRepository
        arguments:
            - '@doctrine'
            - '@terminal42_shortlink.hashids'
            - '@contao.security.token_checker'
